import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type {
  OpenManusExecutionRequest,
  OpenManusExecutionResult,
} from './protocol';

const OUTPUT_MAX_CHARS = 24_000;
const FORCE_KILL_DELAY_MS = 2_000;

export interface OpenManusRuntimeOptions {
  signal?: AbortSignal;
  spawnProcess?: typeof spawn;
}

export async function executeOpenManusRequest(
  request: OpenManusExecutionRequest,
  options: OpenManusRuntimeOptions = {},
): Promise<OpenManusExecutionResult> {
  throwIfAborted(options.signal);

  const spawnProcess = options.spawnProcess ?? spawn;
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'clodex-openmanus-'));
  const configPath = path.join(tmpDir, 'config.toml');

  try {
    await fs.writeFile(configPath, createOpenManusConfig(request), {
      mode: 0o600,
    });

    let stdout = '';
    let stderr = '';
    let timedOut = false;
    const prompt = [
      `Clodex workspace root: ${request.workspacePath}`,
      `Workspace mount prefix: ${request.mountPrefix}`,
      'Operate only inside this workspace. Do not modify files unless the user explicitly asked for changes.',
      '',
      request.prompt,
    ].join('\n');

    const result = await waitForOpenManusProcess({
      spawnProcess,
      request,
      prompt,
      configPath,
      signal: options.signal,
      onStdout: (chunk) => {
        stdout = appendCapped(stdout, chunk);
      },
      onStderr: (chunk) => {
        stderr = appendCapped(stderr, chunk);
      },
      onTimeout: () => {
        timedOut = true;
      },
    });

    const status = timedOut
      ? 'timed out'
      : result.exitCode === 0
        ? 'completed'
        : 'failed';

    return {
      message: `OpenManus ${status}.`,
      exitCode: result.exitCode,
      signal: result.signal ?? undefined,
      timedOut,
      workspacePath: request.workspacePath,
      openManusHome: request.openManusHome,
      stdout: redactSecrets(stdout, [request.apiKey]),
      stderr: redactSecrets(stderr, [request.apiKey]),
    };
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
}

async function waitForOpenManusProcess({
  spawnProcess,
  request,
  prompt,
  configPath,
  signal,
  onStdout,
  onStderr,
  onTimeout,
}: {
  spawnProcess: typeof spawn;
  request: OpenManusExecutionRequest;
  prompt: string;
  configPath: string;
  signal?: AbortSignal;
  onStdout: (chunk: Buffer) => void;
  onStderr: (chunk: Buffer) => void;
  onTimeout: () => void;
}): Promise<{
  exitCode: number | null;
  signal: NodeJS.Signals | null;
}> {
  throwIfAborted(signal);

  return await new Promise((resolve, reject) => {
    let child: ChildProcessWithoutNullStreams;
    let settled = false;
    let forceKillTimeout: ReturnType<typeof setTimeout> | null = null;

    const cleanup = () => {
      clearTimeout(timeout);
      if (forceKillTimeout) clearTimeout(forceKillTimeout);
      signal?.removeEventListener('abort', handleAbort);
    };
    const finish = (callback: () => void) => {
      if (settled) return;
      settled = true;
      cleanup();
      callback();
    };
    const terminate = () => {
      if (child.kill('SIGTERM')) {
        forceKillTimeout = setTimeout(() => {
          child.kill('SIGKILL');
        }, FORCE_KILL_DELAY_MS);
        forceKillTimeout.unref?.();
      }
    };
    const handleAbort = () => {
      terminate();
    };
    const timeout = setTimeout(() => {
      onTimeout();
      terminate();
    }, request.timeoutMs);
    timeout.unref?.();

    try {
      child = spawnProcess(
        request.pythonExecutable,
        ['main.py', '--prompt', prompt],
        {
          cwd: request.openManusHome,
          env: {
            ...request.environment,
            WORKSPACE_ROOT: request.workspacePath,
            OPENMANUS_WORKSPACE_ROOT: request.workspacePath,
            OPENMANUS_CONFIG_PATH: configPath,
          },
          shell: false,
        },
      ) as ChildProcessWithoutNullStreams;
    } catch (error) {
      finish(() => reject(error));
      return;
    }

    child.stdout.on('data', onStdout);
    child.stderr.on('data', onStderr);
    child.on('error', (error) => {
      finish(() => reject(error));
    });
    child.on('close', (exitCode, closeSignal) => {
      if (signal?.aborted) {
        finish(() => reject(createAbortError()));
        return;
      }
      finish(() => resolve({ exitCode, signal: closeSignal }));
    });

    signal?.addEventListener('abort', handleAbort, { once: true });
    if (signal?.aborted) handleAbort();
  });
}

function createOpenManusConfig(request: OpenManusExecutionRequest): string {
  return [
    '# Generated by Clodex IDE for a single OpenManus run.',
    '[llm]',
    `model = ${tomlString(request.modelId)}`,
    `base_url = ${tomlString(request.baseUrl)}`,
    `api_key = ${tomlString(request.apiKey)}`,
    `max_tokens = ${request.maxTokens}`,
    'temperature = 0.0',
    'api_type = "openai"',
    'api_version = ""',
    '',
    '[llm.vision]',
    `model = ${tomlString(request.modelId)}`,
    `base_url = ${tomlString(request.baseUrl)}`,
    `api_key = ${tomlString(request.apiKey)}`,
    `max_tokens = ${request.maxTokens}`,
    'temperature = 0.0',
    'api_type = "openai"',
    'api_version = ""',
    '',
    '[daytona]',
    'daytona_api_key = ""',
    '',
    '[mcp]',
    'server_reference = "app.mcp.server"',
    '',
    '[runflow]',
    'use_data_analysis_agent = false',
    '',
  ].join('\n');
}

function appendCapped(current: string, chunk: Buffer): string {
  const next = current + chunk.toString('utf8');
  if (next.length <= OUTPUT_MAX_CHARS) return next;
  return next.slice(next.length - OUTPUT_MAX_CHARS);
}

function redactSecrets(
  value: string,
  secrets: readonly (string | undefined)[],
): string {
  return secrets.reduce<string>((current, secret) => {
    if (!secret) return current;
    return current.split(secret).join('[REDACTED]');
  }, value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function throwIfAborted(signal: AbortSignal | undefined): void {
  if (signal?.aborted) throw createAbortError();
}

function createAbortError(): Error {
  return new DOMException('OpenManus execution was aborted', 'AbortError');
}
