#!/usr/bin/env bash
# =============================================================================
#  Clodex - Codex installer for macOS
# =============================================================================
#  Sets up the Codex desktop app to use the Clodex gateway
#  (https://clodex.xyz/v1) with your personal API key.
#
#  What it does:
#    1. Validates the API key.
#    2. Gracefully quits Codex if it is running.
#    3. Backs up the existing ~/.codex/{auth.json,config.toml}.
#    4. Writes a fresh auth.json + config.toml pointing at Clodex.
#    5. Registers CLODEX_API_KEY and OPENAI_API_KEY in launchd so they survive reboots.
#    6. Restarts Codex.
#
#  Usage:
#    chmod +x install.sh
#    ./install.sh <YOUR_CLODEX_API_KEY>
#
#  Or set the API key inside this file (API_KEY="..."), then just run ./install.sh
# =============================================================================

set -euo pipefail

# ---------- CONFIG ----------
# Paste your key here OR pass it as the first script argument.
API_KEY="${1:-}"

BASE_URL="${CODEX_BASE_URL:-${CLODEX_BASE_URL:-https://clodex.xyz/v1}}"
DEFAULT_MODEL="gpt-5.4"
PROVIDER_ID="${CODEX_PROVIDER_ID:-clodex}"
PROVIDER_LABEL="${CODEX_PROVIDER_LABEL:-Clodex}"
BRAND_SLUG="${CODEX_BRAND_SLUG:-clodex}"
ENV_VAR_NAME="${CODEX_ENV_VAR_NAME:-CLODEX_API_KEY}"
OPENAI_ENV_VAR_NAME="OPENAI_API_KEY"
AGENT_LABEL="${CODEX_AGENT_LABEL:-com.${BRAND_SLUG}.env}"
# ---------- /CONFIG ----------

CODEX_DIR="$HOME/.codex"
AUTH_PATH="$CODEX_DIR/auth.json"
CONFIG_PATH="$CODEX_DIR/config.toml"
ENV_PATH="$CODEX_DIR/${BRAND_SLUG}.env"
AGENT_DIR="$HOME/Library/LaunchAgents"
AGENT_PATH="$AGENT_DIR/${AGENT_LABEL}.plist"
BACKUP_DIR="$CODEX_DIR/backups/${BRAND_SLUG}-install-$(date +%Y%m%d-%H%M%S)"

# ---------------- 1. Validate API key ----------------
if [[ -z "$API_KEY" || "$API_KEY" == "PASTE_YOUR_KEY_HERE" ]]; then
  echo "Error: API key is missing." >&2
  echo "Run: ./install.sh clodex_xxxxxxxx" >&2
  echo "Or set the key in the API_KEY variable near the top of this file." >&2
  exit 1
fi

if [[ ! "$API_KEY" =~ ^(clodex_|sk-)[A-Za-z0-9._-]{16,}$ ]]; then
  echo "Warning: the key does not look like a Clodex API key." >&2
  echo "Continue anyway? [y/N]" >&2
  read -r answer
  [[ "$answer" =~ ^[yY]$ ]] || exit 1
fi

# ---------------- 2. Quit Codex ----------------
codex_was_running=0
if pgrep -x "Codex" >/dev/null 2>&1; then
  codex_was_running=1
  echo "Closing Codex..."
  osascript -e 'tell application "Codex" to quit' >/dev/null 2>&1 || true
  sleep 2
  pkill -f "/Applications/Codex.app/Contents/MacOS/Codex" >/dev/null 2>&1 || true
fi

# ---------------- 3. Backup ----------------
mkdir -p "$CODEX_DIR" "$AGENT_DIR" "$BACKUP_DIR"
umask 077
[[ -f "$AUTH_PATH"   ]] && cp "$AUTH_PATH"   "$BACKUP_DIR/auth.json"   && echo "Backup: $BACKUP_DIR/auth.json"
[[ -f "$CONFIG_PATH" ]] && cp "$CONFIG_PATH" "$BACKUP_DIR/config.toml" && echo "Backup: $BACKUP_DIR/config.toml"

# ---------------- 4. Write env + auth.json + config.toml ----------------
cat >"$ENV_PATH" <<EOF
export $ENV_VAR_NAME="$API_KEY"
export $OPENAI_ENV_VAR_NAME="$API_KEY"
EOF

cat >"$AUTH_PATH" <<EOF
{
  "auth_mode": "apikey",
  "OPENAI_API_KEY": "$API_KEY"
}
EOF

cat >"$CONFIG_PATH" <<EOF
# Generated by $PROVIDER_LABEL installer on $(date)
model = "$DEFAULT_MODEL"
model_reasoning_effort = "high"
model_provider = "$PROVIDER_ID"

[model_providers.$PROVIDER_ID]
name = "$PROVIDER_LABEL"
base_url = "$BASE_URL"
wire_api = "responses"
env_key = "$ENV_VAR_NAME"
supports_websockets = false
requires_openai_auth = true
EOF

# ---------------- 5. Register launchd env var ----------------
cat >"$AGENT_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$AGENT_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/launchctl</string>
    <string>setenv</string>
    <string>$ENV_VAR_NAME</string>
    <string>$API_KEY</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF

OPENAI_AGENT_LABEL="${AGENT_LABEL}.openai"
OPENAI_AGENT_PATH="$AGENT_DIR/${OPENAI_AGENT_LABEL}.plist"
cat >"$OPENAI_AGENT_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$OPENAI_AGENT_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/launchctl</string>
    <string>setenv</string>
    <string>$OPENAI_ENV_VAR_NAME</string>
    <string>$API_KEY</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF

chmod 600 "$ENV_PATH" "$AUTH_PATH" "$CONFIG_PATH" "$AGENT_PATH" "$OPENAI_AGENT_PATH"

# Apply right now + register at login.
launchctl setenv "$ENV_VAR_NAME" "$API_KEY" >/dev/null 2>&1 || true
launchctl setenv "$OPENAI_ENV_VAR_NAME" "$API_KEY" >/dev/null 2>&1 || true
launchctl bootout  "gui/$(id -u)" "$AGENT_PATH" >/dev/null 2>&1 || true
launchctl bootout  "gui/$(id -u)" "$OPENAI_AGENT_PATH" >/dev/null 2>&1 || true
launchctl bootstrap "gui/$(id -u)" "$AGENT_PATH" >/dev/null 2>&1 || true
launchctl bootstrap "gui/$(id -u)" "$OPENAI_AGENT_PATH" >/dev/null 2>&1 || true

# ---------------- 6. Relaunch Codex ----------------
if [[ "$codex_was_running" == "1" ]] || [[ -d "/Applications/Codex.app" ]]; then
  open -a "Codex" >/dev/null 2>&1 || true
fi

cat <<EOF

============================================================
 Done! Codex is connected to $PROVIDER_LABEL.
============================================================
  Endpoint : $BASE_URL
  Model    : $DEFAULT_MODEL
  Env vars : $ENV_VAR_NAME, $OPENAI_ENV_VAR_NAME
  Env file : $ENV_PATH
  Config   : $CONFIG_PATH
  Backup   : $BACKUP_DIR

  If Codex did not open automatically, start it manually.
  If the environment variable was not picked up, log out and back in.
  Chats and session history were not removed.
============================================================
EOF
