/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PullRequestRouteImport } from './routes/pull-request'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as GeneratedAppsIndexRouteImport } from './routes/generated-apps/index'
import { Route as PreviewAppIdRouteImport } from './routes/preview/$appId'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins/$pluginId'
import { Route as PlanFilenameRouteImport } from './routes/plan/$filename'
import { Route as GeneratedAppsAppKeyRouteImport } from './routes/generated-apps/$appKey'
import { Route as DiffReviewAgentInstanceIdRouteImport } from './routes/diff-review/$agentInstanceId'
import { Route as ErrorPagesErrorPageLoadFailedRouteImport } from './routes/_error-pages/error.page-load-failed'

const PullRequestRoute = PullRequestRouteImport.update({
  id: '/pull-request',
  path: '/pull-request',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratedAppsIndexRoute = GeneratedAppsIndexRouteImport.update({
  id: '/generated-apps/',
  path: '/generated-apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAppIdRoute = PreviewAppIdRouteImport.update({
  id: '/preview/$appId',
  path: '/preview/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanFilenameRoute = PlanFilenameRouteImport.update({
  id: '/plan/$filename',
  path: '/plan/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratedAppsAppKeyRoute = GeneratedAppsAppKeyRouteImport.update({
  id: '/generated-apps/$appKey',
  path: '/generated-apps/$appKey',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffReviewAgentInstanceIdRoute =
  DiffReviewAgentInstanceIdRouteImport.update({
    id: '/diff-review/$agentInstanceId',
    path: '/diff-review/$agentInstanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ErrorPagesErrorPageLoadFailedRoute =
  ErrorPagesErrorPageLoadFailedRouteImport.update({
    id: '/_error-pages/error/page-load-failed',
    path: '/error/page-load-failed',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/pull-request': typeof PullRequestRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/generated-apps/$appKey': typeof GeneratedAppsAppKeyRoute
  '/plan/$filename': typeof PlanFilenameRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/preview/$appId': typeof PreviewAppIdRoute
  '/generated-apps/': typeof GeneratedAppsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/pull-request': typeof PullRequestRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/generated-apps/$appKey': typeof GeneratedAppsAppKeyRoute
  '/plan/$filename': typeof PlanFilenameRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/preview/$appId': typeof PreviewAppIdRoute
  '/generated-apps': typeof GeneratedAppsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/pull-request': typeof PullRequestRoute
  '/diff-review/$agentInstanceId': typeof DiffReviewAgentInstanceIdRoute
  '/generated-apps/$appKey': typeof GeneratedAppsAppKeyRoute
  '/plan/$filename': typeof PlanFilenameRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
  '/preview/$appId': typeof PreviewAppIdRoute
  '/generated-apps/': typeof GeneratedAppsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/_error-pages/error/page-load-failed': typeof ErrorPagesErrorPageLoadFailedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/pull-request'
    | '/diff-review/$agentInstanceId'
    | '/generated-apps/$appKey'
    | '/plan/$filename'
    | '/plugins/$pluginId'
    | '/preview/$appId'
    | '/generated-apps/'
    | '/plugins/'
    | '/skills/'
    | '/error/page-load-failed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/pull-request'
    | '/diff-review/$agentInstanceId'
    | '/generated-apps/$appKey'
    | '/plan/$filename'
    | '/plugins/$pluginId'
    | '/preview/$appId'
    | '/generated-apps'
    | '/plugins'
    | '/skills'
    | '/error/page-load-failed'
  id:
    | '__root__'
    | '/home'
    | '/pull-request'
    | '/diff-review/$agentInstanceId'
    | '/generated-apps/$appKey'
    | '/plan/$filename'
    | '/plugins/$pluginId'
    | '/preview/$appId'
    | '/generated-apps/'
    | '/plugins/'
    | '/skills/'
    | '/_error-pages/error/page-load-failed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  PullRequestRoute: typeof PullRequestRoute
  DiffReviewAgentInstanceIdRoute: typeof DiffReviewAgentInstanceIdRoute
  GeneratedAppsAppKeyRoute: typeof GeneratedAppsAppKeyRoute
  PlanFilenameRoute: typeof PlanFilenameRoute
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
  PreviewAppIdRoute: typeof PreviewAppIdRoute
  GeneratedAppsIndexRoute: typeof GeneratedAppsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  ErrorPagesErrorPageLoadFailedRoute: typeof ErrorPagesErrorPageLoadFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pull-request': {
      id: '/pull-request'
      path: '/pull-request'
      fullPath: '/pull-request'
      preLoaderRoute: typeof PullRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generated-apps/': {
      id: '/generated-apps/'
      path: '/generated-apps'
      fullPath: '/generated-apps/'
      preLoaderRoute: typeof GeneratedAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$appId': {
      id: '/preview/$appId'
      path: '/preview/$appId'
      fullPath: '/preview/$appId'
      preLoaderRoute: typeof PreviewAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$filename': {
      id: '/plan/$filename'
      path: '/plan/$filename'
      fullPath: '/plan/$filename'
      preLoaderRoute: typeof PlanFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generated-apps/$appKey': {
      id: '/generated-apps/$appKey'
      path: '/generated-apps/$appKey'
      fullPath: '/generated-apps/$appKey'
      preLoaderRoute: typeof GeneratedAppsAppKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff-review/$agentInstanceId': {
      id: '/diff-review/$agentInstanceId'
      path: '/diff-review/$agentInstanceId'
      fullPath: '/diff-review/$agentInstanceId'
      preLoaderRoute: typeof DiffReviewAgentInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_error-pages/error/page-load-failed': {
      id: '/_error-pages/error/page-load-failed'
      path: '/error/page-load-failed'
      fullPath: '/error/page-load-failed'
      preLoaderRoute: typeof ErrorPagesErrorPageLoadFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  PullRequestRoute: PullRequestRoute,
  DiffReviewAgentInstanceIdRoute: DiffReviewAgentInstanceIdRoute,
  GeneratedAppsAppKeyRoute: GeneratedAppsAppKeyRoute,
  PlanFilenameRoute: PlanFilenameRoute,
  PluginsPluginIdRoute: PluginsPluginIdRoute,
  PreviewAppIdRoute: PreviewAppIdRoute,
  GeneratedAppsIndexRoute: GeneratedAppsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  ErrorPagesErrorPageLoadFailedRoute: ErrorPagesErrorPageLoadFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
