#!/usr/bin/env tsx

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const browserRoot = path.resolve(scriptDirectory, '..');

await build({
  entryPoints: [path.join(scriptDirectory, 'remote-control-client.ts')],
  outfile: path.join(
    browserRoot,
    'src/backend/services/agent-os/remote-control-client.bundle.js',
  ),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  legalComments: 'none',
  sourcemap: false,
  banner: {
    js: '/* Generated by scripts/bundle-remote-control-client.ts. */',
  },
});

console.log('[remote-control] Browser crypto client bundle updated.');
